name: paper-community-fa2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - lxml              # 读写 GEXF 用
  - pip
  - pip:
      - "networkx<2.0"   # ★ 从 PyPI 安装 1.x（fa2l 需要）
      - fa2l==0.2        # ★ 只有函数接口：forceatlas2_networkx_layout
      - tqdm